### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by GiulioRossetti** [benedekrozemberczki/karateclub#133] opened 2023-03-14 13:55 UTC
Hi @benedekrozemberczki ,

will it be possible to make the version requirements for numpy, networkx and pandas a little less stringent?

We are trying to update the dependency list of [cdlib](https://github.com/GiulioRossetti/cdlib) but it seems that the latest versions of such packages break all our krarateclub integrations.

Best,
Giulio

**Comment by benedekrozemberczki** [comment] 2023-03-14 21:35
Hi @GiulioRossetti , I will look into this.

**Comment by WhatTheFuzz** [comment] 2023-03-22 13:43
I can confirm that `networkx` 3.0 < makes breaking changes, as shown in the test cases.

```shell
FAILED test/community_detection_overlapping_test.py::test_danmf - ValueError: inconsistent shapes
====================== 1 failed, 46 passed, 851 warnings in 195.31s (0:03:15) =======================
```

This may be related to the change `networkx` 3.0 < made to return sparse arrays instead of matrices when calling certain methods. See one deprecation warning below.

```shell
test/community_detection_overlapping_test.py::test_danmf
test/community_detection_overlapping_test.py::test_danmf
  /home/siuser/Developer/karateclub/karateclub/community_detection/overlapping/danmf.py:48: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
    self._A = nx.adjacency_matrix( 
```

To recreate this issue, just bump `networkx` dependency in `setup.py` to `"networkx==3.0",`

**Comment by rjurney** [comment] 2023-06-08 00:21
I need pandas 2.0. I can't use this :(

**Comment by rjurney** [comment] 2023-06-08 00:23
@WhatTheFuzz can you let me know what other issues involving networkx 3.0 are? I really want to include `karateclub` in my Graph ML class and am willing to do the work if it isn't too extensive.

**Comment by rjurney** [comment] 2023-06-08 00:45
Ok, FWIW I am poking around here :) 

```python
install_requires = [
    "numpy>=1.22.0",
    "networkx>=3.0",
    "decorator==5.1.*",
    ...
```

**Comment by rjurney** [comment] 2023-06-27 04:19
I got a little experience in this PR: https://github.com/benedekrozemberczki/littleballoffur/pull/23

I am going to make karateclub go with `networkx>=3.1` now :)

**Comment by WhatTheFuzz** [comment] 2023-06-27 20:47
Sorry, I didn't mean to leave you hanging! I was just going off of the unit tests before. I'm not exactly the best ML dev out there. I would definitely love to bump the dependencies so I can update my environments. Happy to bounce ideas off though.

**Comment by benedekrozemberczki** [comment] 2023-07-01 21:45
Hi there @rjurney do you want to go ahead?

**Comment by gkirgizov** [comment] 2023-08-14 06:30
As I see, in https://github.com/benedekrozemberczki/karateclub/blob/master/setup.py you have already relaxed requirements. But PyPi release still has quite strict requirements that get in the way with almost any other recent package. We got into install problem because of that in our project https://github.com/aimclub/GOLEM.

Could you consider making a minor release soon with updated dependencies?

**Comment by rjurney** [comment] 2023-08-15 22:24
@gkirgizov I am going to get back to this soon!

**Comment by rjurney** [comment] 2023-10-05 18:12
Oh shit, this is that scikit-learn bug I ran into :( Woe is me, I've got just half an hour to try!

**Comment by rjurney** [comment] 2023-10-05 18:53
Gentlemen [ @benedekrozemberczki and @GiulioRossetti @WhatTheFuzz @gkirgizov ] please check out #150 🥳 

Everything works in networkx 3.3 now! All unit tests pass. Please examine and merge 😁

**Comment by LucaCappelletti94** [comment] 2024-02-22 17:03
Closing issue as PR was merged.

**Closed by LucaCappelletti94** 2024-02-22 17:03 UTC
